export const LOCAL_ROOT_HOSTNAME = process.env['NEXT_PUBLIC_LOCAL_ROOT_HOSTNAME'] || 'localhost'
export const LOCAL_ROOT_HOST = `${LOCAL_ROOT_HOSTNAME}:${process.env['PORT'] || 3000}`
export const LOCAL_ROOT_ORIGIN = `http://${LOCAL_ROOT_HOST}`

export const PROD_ROOT_HOSTNAME =
  process.env['NEXT_PUBLIC_SITE_URL']
  || process.env['NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL']
  || process.env['VERCEL_URL']
export const PROD_ROOT_ORIGIN = PROD_ROOT_HOSTNAME && `https://${PROD_ROOT_HOSTNAME}`

export const ROOT_HOSTNAME = PROD_ROOT_HOSTNAME || LOCAL_ROOT_HOSTNAME
export const ROOT_HOST = PROD_ROOT_HOSTNAME || LOCAL_ROOT_HOST
export const ROOT_ORIGIN = PROD_ROOT_ORIGIN || LOCAL_ROOT_ORIGIN
